baseURL: http://mikezornek.com
name: Mike Zornek
description: Sharing life and geek notes from Philadelphia.
title: Mike Zornek
languageCode: "en-us"
pygmentsCodeFences: true
pygmentsStyle: tango
pygmentsCodefencesGuessSyntax: true
menu:
  main:
  - name: Home
    url: /
    weight: 10
  - name: Contact
    url: /contact/
    weight: 20
  - name: Events
    url: /events/
    weight: 30
  - name: Micro.Blog ↗️ 
    url: http://microblog.mikezornek.com/
    weight: 40

