version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.52
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v -t hugo_theme_pickles
      - run:
          name: "Test Website"
          command: htmlproofer public --allow-hash-href --check-html --empty-alt-ignore --disable-external
      - add_ssh_keys
      - run:
          name: "Add HostKeys"
          command: echo $HOSTKEY1 >> ~/.ssh/known_hosts && echo $HOSTKEY2 >> ~/.ssh/known_hosts && echo $HOSTKEY3 >> ~/.ssh/known_hosts
      - deploy:
          name: "Deploy"
          command: rsync -vaz --delete public/ zorn@45.79.149.225/var/www/html/beta.mikezornek.com/public_html/
